name: mirai_dev_order_monitoring
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: ^2.1.0
  firebase_auth: ^4.0.2
  cloud_firestore: ^4.0.2
  firebase_storage: ^11.0.2
  flutter_screenutil: ^5.5.4
  shimmer: ^2.0.0
  font_awesome_flutter: ^10.2.1
  flutter_svg: ^1.1.6
  string_validator: ^0.3.0
  salomon_bottom_bar: ^3.3.1
  pie_chart: ^5.3.2
  url_launcher: ^6.1.8
  syncfusion_flutter_pdf: ^20.4.44
  open_filex: ^4.3.2
  permission_handler: ^10.2.0
  path_provider: ^2.0.12
  loading_animation_widget: ^1.2.0+4
  equatable: ^2.0.5
  google_maps_flutter: ^2.2.5
  google_maps_flutter_web: ^0.5.0+1
  photo_view: ^0.14.0
  file_picker: ^5.2.3


  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

